### ISSUE TITLE
Workflow configuration not visible

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-studio#171]
**Describe the bug**
After publishing a specific workflow, the configuration is present in firestore at the right place but not visible in Jarvis Studio

**To Reproduce**
In Firebase, Firestore > worflow-configuration, look for the "workflow_000010_load_PDA_rfid_retail_reload" configuration
In Studio look for the same configuration in the workflow configurations listing. It's not visible :(

**Expected behavior**
The "workflow_000010_load_PDA_rfid_retail_reload" must be visible in the workflow configurations listing

**Screenshots**

**Comment by Eronne** [comment]
This is an issue with data stored in firestore. In fact I identified two workflow configurations having the issue:
- `workflow_000010_load_BDA_rfid_retail_reload`
- `workflow_000010_load_PDA_rfid_retail_reload`

They are both using an `archived` field instead of an `archive` field. In studio we have a filter on this field and if it doesn't exists, doc is never going to be fetched.

**Comment by romone22** [comment]
Ok many thanks !!! 

I better andre stand the issu. 
Many thanks.

**Comment by Eronne** [comment]
We have to support `archive` & `archived` fields for the moment
